name: intouch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  lottie: ^2.6.0
  firebase_core: ^2.15.0
  firebase_ui_auth: ^1.6.2
  firebase_ui_firestore: ^1.5.6
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

fonts:
    - family: googlesans
      fonts:
        - asset: fonts/googlesans_regular.ttf
        - asset: fonts/googlesans_regular_italic.ttf
          style: regular_italic
        - asset: fonts/googlesans_medium.ttf
          style: medium
        - asset: fonts/googlesans_medium_italic.ttf
          style: medium_italic
        - asset: fonts/googlesans_bold.ttf
          style: bold
        - asset: fonts/googlesans_bold_italic-ttf
          style: bold_italic
    - family: righteous
      fonts:
        - asset: fonts/righteous.ttf

flutter:
  uses-material-design: true
  assets:
     - assets/anim/
     - assets/images/
    